vscode:
  extensions:
    - hollowtree.vue-snippets@0.1.11:6Eh/noAzUlIM2G8pAmdZqA==
    - thekalinga.bootstrap4-vscode@6.1.0:duaQhthWtxWBzXAGe+5GKQ==
    - peakchen90.vue-beautify@2.0.4:drPwPJo2Mx92PILu3HZqNQ==
    - vuetifyjs.vuetify-vscode@0.2.0:NJwDb7TtN4HKH0hc44vIlw==
    - teabyii.ayu@0.18.0:43zsEDFuC6dcxhBPBJlJlg==